export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'auth/LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'auth/LOGIN_REQUEST_FAILURE';
export const LOGOUT = 'auth/LOGOUT';
